### ISSUE TITLE
Persistance with Auto-export modes

### ISSUE THREAD

**Issue by JulianVolodia** [nccgroup/LoggerPlusPlus#110]
**Feature description:**
I want persistance of auto-export settings across Burp Suite runtimes (but for me only CSV is needed).

**Scenario example:**
When opening project again, Logger++ will have settings like Auto-export as CSV enabled with customized options enabled across multiple runtime cycles (saved when exiting app or during setting logger up).

This would increase reliability of its work (as now one could forgot to set it up again).

![image](https://user-images.githubusercontent.com/1219023/88582023-5298e600-d04e-11ea-8d91-d94a3ca89a16.png)

**Comment by JulianVolodia** [comment]
If You know some work-around or my lack of proper manage of Logger++ tell me. I am open for suggestions as well to contribution.

**Comment by JulianVolodia** [comment]
Hmm... but #99 smells like very similar but not general but only Elasticsearch auto-logger persistance setup.

**Comment by CoreyD97** [comment]
Thanks for the suggestion! Is #96 along the lines of what you were thinking?

It allows field lists to be saved as profiles, and will automatically use the previously configured list, although this does not include any auto start functionality as CSV needs a bit more configuring between runs than elasticsearch.

Let me know if this is what you were thinking.

**Comment by JulianVolodia** [comment]
Hey, I reviewed fastly reffered issue. I think it could be solution, but at most I rather want to have:
- persistance for project not shared profile (bc if you change profile once then you probably don't want other projects be influenced but to be like they was, isn't it?)
- better selection options bc list of (Field, Enabled) don't support select range /(with Shift pressed) and enable it (with space, as work when one item is selected)

**Comment by CoreyD97** [comment]
I see, the profiles are mainly intended to make it easy to switch between sets of fields for different kinds of exports.

When Burp is closed and reopened it saves the last used set of fields. This might be shared between all projects at the moment but this could easily modified to save it per project instead.

As for the selections, this is something I will implement also.

**Comment by JulianVolodia** [comment]
Hey @CoreyD97 Could I do something in this or other subject?

**Comment by CoreyD97** [comment]
Hey, any help is greatly appreciated! Sorry for the delay in getting this implemented, I haven't had a lot of time to work on this recently.

**Comment by JulianVolodia** [comment]
No problem. I also have not much time.

**Comment by CoreyD97** [comment]
No worries, I'll try to take a look at this soon for you then.

I'll keep the export profiles shared between all projects, since these could just be named differently for different usages, but will make sure the project remembers the last used selection. 

As for the multi selecting of export fields, I'll implement this!

**Comment by CoreyD97** [comment]
Sorry, reading through your comments again I feel like I completely misinterpreted your suggestion. I've had a look tonight but unfortunately, it seems that the amount of work it would take to implement this outweighs the benefits. 

However, I've improved the field selector dialog since your original report, so it should be easy enough to save a preset for the fields to be exported, so you don't have to reselect each of these when enabling the exporter.
