### ISSUE TITLE
Feature request...Get log from turbo intruder

### ISSUE THREAD

**Issue by Lokesh-Reddy-plvd** [nccgroup/LoggerPlusPlus#117]
**Feature description:**
I want...to get log from turbo intruder. As this (Logger++) is great tool to get log from all tools. But, I'm not getting any log from extension "Turbo Intruder". 

If you can add this feature, it would be very great full.

**Scenario example:**
This would be very useful as turbo intruder extension is very fast compared to existing intruder. Logger++ has lots of features to export/import data for analysis....

**Comment by CoreyD97** [comment]
Thank you for your request @Lokesh-Reddy-plvd. In order to achieve its exceptional speed, Turbo Intruder implements its own HTTP stack with a number of tweaks and as such does not pass its requests through Burp Suite by default.

However, you can force Turbo Intruder to use Burp Suite's HTTP stack to see the requests in Logger++ by using the following:
```python
    engine = RequestEngine(endpoint=target.endpoint,
                           concurrentConnections=5,
                           engine=Engine.BURP # Use Burp's network stack, including upstream proxies etc
                           )
```
