### ISSUE TITLE
Persist Auto-Save Settings and Auto-Import on Restart

### ISSUE THREAD

**Issue by a-marionette** [nccgroup/LoggerPlusPlus#129]
**Feature description:**
Hello,

The requested feature is to enable persistent auto-save setting so it only needs to be set up this way once, regardless of project.  Additionally, these logs should be auto imported when ever Burp is restarted.

**Scenario example:**
The requested feature would help users better preserve log data and prevent human errors. It would also make the tool require less overall steps.

**Comment by CoreyD97** [comment]
Thanks for the suggestion. Mind to clarify which auto-save setting you're referencing? The Elastic exporter already has persistent auto saving, but others aren't implemented yet due to various limitations.

I've got plans to also allow entries to be stored in a CouchDB instance, which would make importing much easier in future too, and would also store requests from all tools and not just the proxy.

**Comment by C0DEbrained** [comment]
Unfortunately this isn't feasible without a substantial rewrite.
