### ISSUE TITLE
Logger++ filter import and saving err

### ISSUE THREAD

**Issue by breaking153** [nccgroup/LoggerPlusPlus#188]
![图片](https://github.com/nccgroup/LoggerPlusPlus/assets/49428332/8fc74183-8f0c-498e-b1ed-e03008221ac7)
and i cant import filter that i saved before

**Comment by C0DEbrained** [comment]
Tha ks for flagging this. This is the first time I've been made aware of this happening, but may have occurred due to a corrupted preference store.

Unfortunately, I don't think it will be possible to recover your settings but I'll try to add in some extra logic to help recover these values should this happen again in the future.

**Comment by breaking153** [comment]
this will trigger when i was greping values and stuck.then i try to reload the extension and my config is all gone

**Comment by C0DEbrained** [comment]
Really sorry to hear that. Unfortunately if Burp Suite crashes, there is a chance that settings may not be saved.

If you've got a lot of filters etc saved, I recommend exporting them as a string and saving them somewhere safe as a backup.
