### ISSUE TITLE
Exporting logs does not display 'Number column' correctly

### ISSUE THREAD

**Issue by 3thmanE** [nccgroup/LoggerPlusPlus#84]
Example attached. The number displays in View Logs but not when exporting to a CSV. 

**Steps to reproduce:** 
1. Run any of the Burp tools to generate some data in Logger++ 
2. Logger++ > Options > Save log table as CSV/Save full logs as CSV (slow)
3. Check log file. It should display 0 on each entry (like below) 

![Screenshot 2020-02-14 at 11 03 58](https://user-images.githubusercontent.com/60008549/74525717-b8b70400-4f19-11ea-9712-22b1547bf098.png)

Can you please fix this? 

Workaround for me is to just open the CSV with Atom and use the line numbers for reference.

**Comment by CoreyD97** [comment]
Thanks for raising this issue. I'm going to overhaul the exporting options in the future, so will make sure to fix this then. Sorry for any inconvenience!

**Comment by 3thmanE** [comment]
Thanks!

**Comment by CoreyD97** [comment]
Is there a particular reason you wish to export the line numbers? As they are calculated at runtime by the table itself, the log entries don't actually contain this information so it is not something that is easily included when exporting.

If you have a specific need for this I can try to find a workaround, otherwise I think the export of the number column will be removed for future releases.

**Comment by 3thmanE** [comment]
There is no specific reason. I noticed that it was exported and not showing the line numbers correctly. Removing it entirely would be great because you can just open it in a text editor and get that information.

**Comment by CoreyD97** [comment]
Perfect, thanks for the response. I'll close this ticket!
